### PR TITLE
Added enumerated options for sourcing the OpenAI API key and added multicall support

### PR DESCRIPTION
**Pull request by uptudev**
This change modifies the files in the `models` directory in order to create an internal system to handle the API keys. Currently, the method to get API keys is chosen via a setter method on the GPT4 struct, `with_key(OpenAIKeySrc)`. This also adds the optional fallback key source, so failure to resolve in the first method will fallback to a second one. If fallback is set to `OpenAIKeySrc::USERIN` and `human_fallback_enabled` is true, input is prompted for indefinitely until valid input is given.

The way to instantiate a GPT4 struct is now as follows:
```rust
use agents::models::{GPT4, OpenAIKeySrc};

// defaults to the value in `.env` with no fallback
let model = GPT4::new();

// `.env` with human input fallback
let model_2 = GPT4::new()
        .fallback(OpenAIKeySrc::USERIN);

// `std::env` with `.env` fallback
let model_3 = GPT4::new()
        .with_key(OpenAIKeySrc::SYSENV)
        .fallback(OpenAIKeySrc::DOTENV);
```

### CODE REVIEW

**Comment by uptudev** [comment]
Forgot to add the `human_fallback(bool)` setter; force pushed it into PR with resolved merge conflicts.

**Comment by uptudev** [comment]
Added multicall support in this PR as well

**Comment by notdanilo** [comment]
Can you separate it in another PR? I have some concerns about the current PR. I will write about them when I have some free time

**Comment by uptudev** [comment]
I'll close it and branch off the enumeration stuff then.

**Pull request closed without merging**
